/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PourquoiNousRouteImport } from './routes/pourquoi-nous'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssuranceHabitationRouteImport } from './routes/assurance-habitation'
import { Route as AssuranceAutoRouteImport } from './routes/assurance-auto'
import { Route as IndexRouteImport } from './routes/index'

const PourquoiNousRoute = PourquoiNousRouteImport.update({
  id: '/pourquoi-nous',
  path: '/pourquoi-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceHabitationRoute = AssuranceHabitationRouteImport.update({
  id: '/assurance-habitation',
  path: '/assurance-habitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceAutoRoute = AssuranceAutoRouteImport.update({
  id: '/assurance-auto',
  path: '/assurance-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance-auto': typeof AssuranceAutoRoute
  '/assurance-habitation': typeof AssuranceHabitationRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/pourquoi-nous': typeof PourquoiNousRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance-auto': typeof AssuranceAutoRoute
  '/assurance-habitation': typeof AssuranceHabitationRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/pourquoi-nous': typeof PourquoiNousRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance-auto': typeof AssuranceAutoRoute
  '/assurance-habitation': typeof AssuranceHabitationRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/pourquoi-nous': typeof PourquoiNousRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance-auto'
    | '/assurance-habitation'
    | '/contact'
    | '/devis'
    | '/pourquoi-nous'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assurance-auto'
    | '/assurance-habitation'
    | '/contact'
    | '/devis'
    | '/pourquoi-nous'
  id:
    | '__root__'
    | '/'
    | '/assurance-auto'
    | '/assurance-habitation'
    | '/contact'
    | '/devis'
    | '/pourquoi-nous'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceAutoRoute: typeof AssuranceAutoRoute
  AssuranceHabitationRoute: typeof AssuranceHabitationRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  PourquoiNousRoute: typeof PourquoiNousRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pourquoi-nous': {
      id: '/pourquoi-nous'
      path: '/pourquoi-nous'
      fullPath: '/pourquoi-nous'
      preLoaderRoute: typeof PourquoiNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-habitation': {
      id: '/assurance-habitation'
      path: '/assurance-habitation'
      fullPath: '/assurance-habitation'
      preLoaderRoute: typeof AssuranceHabitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-auto': {
      id: '/assurance-auto'
      path: '/assurance-auto'
      fullPath: '/assurance-auto'
      preLoaderRoute: typeof AssuranceAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceAutoRoute: AssuranceAutoRoute,
  AssuranceHabitationRoute: AssuranceHabitationRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  PourquoiNousRoute: PourquoiNousRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
